app = "just-ingredients-bot"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  RUST_LOG = "warn,just_ingredients=info,sqlx=warn"
  LOG_FORMAT = "json"
  OCR_LANGUAGES = "eng+fra"
  CIRCUIT_BREAKER_THRESHOLD = "5"
  CIRCUIT_BREAKER_TIMEOUT_SECS = "60"
  HEALTH_PORT = "8080"
  METRICS_PORT = "8080"
  METRICS_BIND_ALL_INTERFACES = "true"
  MEASUREMENT_UNITS_CONFIG_PATH = "/app/config/measurement_units.json"
  DATABASE_MAX_CONNECTIONS = "5"
  OCR_MEMORY_LIMIT_MB = "80"
  DATABASE_CONNECT_TIMEOUT_SECS = "15"
  HTTP_CLIENT_TIMEOUT_SECS = "20"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
