app = "just-ingredients-bot"
primary_region = "cdg"

[env]
  RUST_LOG = "info,sqlx=warn"
  LOG_FORMAT = "json"
  OCR_LANGUAGES = "eng+fra"
  CIRCUIT_BREAKER_THRESHOLD = "5"
  CIRCUIT_BREAKER_TIMEOUT_SECS = "60"
  HEALTH_PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048
