app = "just-ingredients-monitoring"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile.monitoring"

[env]
  GF_SECURITY_ADMIN_PASSWORD = "admin"
  GF_USERS_ALLOW_SIGN_UP = "false"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
