app = "just-ingredients-monitoring"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile.monitoring"

[env]
  GF_SECURITY_ADMIN_PASSWORD = "admin"
  GF_USERS_ALLOW_SIGN_UP = "false"

# Grafana service
[[services]]
  internal_port = 3000
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "requests"
    soft_limit = 1000
    hard_limit = 1500

# Prometheus service
[[services]]
  internal_port = 9090
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 9090
    handlers = ["http"]

  [services.concurrency]
    type = "requests"
    soft_limit = 1000
    hard_limit = 1500

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
