name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Fly CLI
      run: curl -L https://fly.io/install.sh | sh
      env:
        FLYCTL_INSTALL: /home/runner

    - name: Add Fly CLI to PATH
      run: echo "/home/runner/.fly/bin" >> $GITHUB_PATH

    - name: Deploy to Fly.io
      run: fly deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}